import { NextResponse } from "next/server";
import { gloesim, GloEsimVendorPackage } from "@/app/lib/gloesim";

// Fallback mapped to all 15 official GloEsim packages with actual vendor prices
const FALLBACK_VENDOR_PACKAGES: GloEsimVendorPackage[] = [
  {
    id: "a2db1997-864a-4f10-8449-ad910e8bb318",
    name: "1GB eSIM Data for 3 Days in Pakistan",
    price: 0.87,
    data_quantity: 1,
    data_unit: "GB",
    package_validity: 3,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 242,
    retailPriceUSD: 0.87,
    dataFormatted: "1 GB",
    validityFormatted: "3 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1d6-8635-4ea9-9bcf-a13b942cb37c",
    name: "1GB eSIM Data for 5 Days in Pakistan",
    price: 1.28,
    data_quantity: 1,
    data_unit: "GB",
    package_validity: 5,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 356,
    retailPriceUSD: 1.28,
    dataFormatted: "1 GB",
    validityFormatted: "5 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1d6-e316-41a7-bb79-a28ba1685f10",
    name: "1GB eSIM Data for 7 Days in Pakistan",
    price: 1.37,
    data_quantity: 1,
    data_unit: "GB",
    package_validity: 7,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 382,
    retailPriceUSD: 1.37,
    dataFormatted: "1 GB",
    validityFormatted: "7 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1d7-4ad9-4ca1-a5f5-e031afb9b461",
    name: "1GB eSIM Data for 30 Days in Pakistan",
    price: 1.43,
    data_quantity: 1,
    data_unit: "GB",
    package_validity: 30,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 398,
    retailPriceUSD: 1.43,
    dataFormatted: "1 GB",
    validityFormatted: "30 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1d7-81e4-42db-bd77-f1fa9c9d6501",
    name: "2GB eSIM Data for 3 Days in Pakistan",
    price: 1.56,
    data_quantity: 2,
    data_unit: "GB",
    package_validity: 3,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 434,
    retailPriceUSD: 1.56,
    dataFormatted: "2 GB",
    validityFormatted: "3 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db199b-0e61-479e-bf68-5360eb98ab60",
    name: "3GB eSIM Data for 3 Days in Pakistan",
    price: 1.88,
    data_quantity: 3,
    data_unit: "GB",
    package_validity: 3,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 524,
    retailPriceUSD: 1.88,
    dataFormatted: "3 GB",
    validityFormatted: "3 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db199b-62c9-46f8-a6de-3b85795b4ab3",
    name: "3GB eSIM Data for 7 Days in Pakistan",
    price: 2.24,
    data_quantity: 3,
    data_unit: "GB",
    package_validity: 7,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 624,
    retailPriceUSD: 2.24,
    dataFormatted: "3 GB",
    validityFormatted: "7 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db199d-5103-4c71-9a60-3dabfda83375",
    name: "3GB eSIM Data for 30 Days in Pakistan",
    price: 2.30,
    data_quantity: 3,
    data_unit: "GB",
    package_validity: 30,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 641,
    retailPriceUSD: 2.30,
    dataFormatted: "3 GB",
    validityFormatted: "30 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db19a0-a23d-45a7-a674-d2fd114c8410",
    name: "5GB eSIM Data for 7 Days in Pakistan",
    price: 2.89,
    data_quantity: 5,
    data_unit: "GB",
    package_validity: 7,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 805,
    retailPriceUSD: 2.89,
    dataFormatted: "5 GB",
    validityFormatted: "7 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1e1-210d-43e7-8300-f966d74ca90e",
    name: "5GB eSIM Data for 15 Days in Pakistan",
    price: 2.97,
    data_quantity: 5,
    data_unit: "GB",
    package_validity: 15,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 827,
    retailPriceUSD: 2.97,
    dataFormatted: "5 GB",
    validityFormatted: "15 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db19a1-e566-4505-9c42-879bb6e6c52c",
    name: "5GB eSIM Data for 30 Days in Pakistan",
    price: 3.04,
    data_quantity: 5,
    data_unit: "GB",
    package_validity: 30,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 847,
    retailPriceUSD: 3.04,
    dataFormatted: "5 GB",
    validityFormatted: "30 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db19a7-0def-43c3-8a43-61f4aee699b5",
    name: "10GB eSIM Data for 7 Days in Pakistan",
    price: 4.52,
    data_quantity: 10,
    data_unit: "GB",
    package_validity: 7,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 1259,
    retailPriceUSD: 4.52,
    dataFormatted: "10 GB",
    validityFormatted: "7 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2dab1eb-0415-444f-96ea-9fdbffa4470c",
    name: "10GB eSIM Data for 15 Days in Pakistan",
    price: 4.72,
    data_quantity: 10,
    data_unit: "GB",
    package_validity: 15,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 1315,
    retailPriceUSD: 4.72,
    dataFormatted: "10 GB",
    validityFormatted: "15 Days",
    tier: "Standard",
    popular: false,
  },
  {
    id: "a2db19a9-0a35-4ed8-883f-296d8fe6abf8",
    name: "10GB eSIM Data for 30 Days in Pakistan",
    price: 5.32,
    data_quantity: 10,
    data_unit: "GB",
    package_validity: 30,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 1482,
    retailPriceUSD: 5.32,
    dataFormatted: "10 GB",
    validityFormatted: "30 Days",
    tier: "Popular",
    popular: true,
  },
  {
    id: "a2db19b1-fa96-4a80-b723-3a1d83035201",
    name: "20GB eSIM Data for 30 Days in Pakistan",
    price: 8.80,
    data_quantity: 20,
    data_unit: "GB",
    package_validity: 30,
    package_validity_unit: "Day",
    package_type: "DATA-ONLY",
    connectivity: "2G,3G,4G",
    activation_type_description: "eSim activates when first byte of data is consumed",
    networks: ["Jazz", "Orange", "Jazz Pakistan"],
    retailPricePKR: 2451,
    retailPriceUSD: 8.80,
    dataFormatted: "20 GB",
    validityFormatted: "30 Days",
    tier: "Heavy",
    popular: false,
  },
];

export async function GET() {
  try {
    const livePackages = await gloesim.getVendorPackages(92);

    if (livePackages && livePackages.length > 0) {
      return NextResponse.json({
        success: true,
        source: "live_vendor",
        provider: "GloEsim Enterprise",
        country: "Pakistan",
        countryId: 92,
        count: livePackages.length,
        packages: livePackages,
      });
    }

    return NextResponse.json({
      success: true,
      source: "cached_fallback",
      provider: "GloEsim Enterprise",
      country: "Pakistan",
      countryId: 92,
      count: FALLBACK_VENDOR_PACKAGES.length,
      packages: FALLBACK_VENDOR_PACKAGES,
    });
  } catch (error: any) {
    console.error("[Packages API Error]", error);
    return NextResponse.json({
      success: true,
      source: "fallback",
      provider: "GloEsim Enterprise",
      country: "Pakistan",
      count: FALLBACK_VENDOR_PACKAGES.length,
      packages: FALLBACK_VENDOR_PACKAGES,
    });
  }
}
